//
//  APIConstants.swift
//  GameSwiftUI
//
//  Created by Joshi on 07.04.21.
//

import Foundation
struct APIConstants {
    struct AgeRating {
        static let _base = "age_ratings"
        static let category = "category"
        static let checksum = "checksum"
        static let contentDescriptions = "content_descriptions"
        static let rating = "rating"
        static let ratingCoverUrl = "rating_cover_url"
        static let synopsis = "synopsis"
    }
    
    struct AgeRatingContentDescription {
        static let _base = "age_rating_content_descriptions"
        static let category = "category"
        static let checksum = "checksum"
        static let description = "description"
    }
    
    struct AlternativeName {
        static let _base = "alternative_names"
        static let checksum = "checksum"
        static let comment = "comment"
        static let game = "game"
        static let name = "name"
    }
    struct Artwork {
        static let _base = "artworks"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let game = "game"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct Character {
        static let _base = "characters"
        static let akas = "akas"
        static let checksum = "checksum"
        static let countryName = "country_name"
        static let createdAt = "created_at"
        static let description = "description"
        static let games = "games"
        static let gender = "gender"
        static let mugShot = "mug_shot"
        static let name = "name"
        static let slug = "slug"
        static let species = "species"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct CharacterMugShot {
        static let _base = "chracter_mug_shots"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct Collection {
        static let _base = "collections"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let games = "games"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct Company {
        static let _base = "companies"
        static let changeDate = "change_date"
        static let changeDateCategory = "change_date_category"
        static let changedCompanyId = "changed_company_id"
        static let checksum = "checksum"
        static let country = "country"
        static let createdAt = "created_at"
        static let description = "description"
        static let developed = "developed"
        static let logo = "logo"
        static let name = "name"
        static let parent = "parent"
        static let published = "published"
        static let slug = "slug"
        static let startDate = "start_date"
        static let startDateCategory = "start_date_category"
        static let updatedAt = "updated_at"
        static let url = "url"
        static let websites = "websites"
    }
    struct CompanyLogo {
        static let _base = "company_logos"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct CompanyWebsite {
        static let _base = "company_websites"
        static let category = "category"
        static let checksum = "checksum"
        static let trusted = "trusted"
        static let url = "url"
    }
    struct Cover {
        static let _base = "cover"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let game = "game"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct ExternalGame {
        static let _base = "external_games"
        static let category = "category"
        static let checksum = "checksum"
        static let countries = "countries"
        static let createdAt = "created_at"
        static let game = "game"
        static let media = "media"
        static let name = "name"
        static let platform = "platform"
        static let uid = "uid"
        static let updatedAt = "updated_at"
        static let url = "url"
        static let year = "year"
    }
    
    struct Franchise {
        static let _base = "franchises"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let games = "games"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    
    struct Game {
        static let _base = "games"
        static let ageRatings = "age_ratings"
        static let aggregatedRating = "aggregated_rating"
        static let aggregatedRatingCount = "aggregated_rating_count"
        static let alternativeNames = "alternative_names"
        static let artworks = "artworks"
        static let bundles = "bundles"
        static let category = "category"
        static let checksum = "checksum"
        static let collection = "collection"
        static let cover = "cover"
        static let createdAt = "created_at"
        static let dlcs = "dlcs"
        static let expandedGames = "expanded_games"
        static let expansions = "expansions"
        static let externalGames = "external_games"
        static let firstReleaseDate = "first_release_date"
        static let follows = "follows"
        static let forks = "forks"
        static let franchise = "franchise"
        static let franchises = "franchises"
        static let gameEngines = "game_engines"
        static let gameModes = "game_modes"
        static let genres = "genres"
        static let hypes = "hypes"
        static let involvedCompanies = "involved_companies"
        static let keywords = "keywords"
        static let multiplayerModes = "multiplayer_modes"
        static let name = "name"
        static let parentGame = "parent_game"
        static let platforms = "platforms"
        static let playerPerspectives = "player_perspectives"
        static let ports = "ports"
        static let rating = "rating"
        static let ratingCount = "rating_count"
        static let releaseDates = "release_dates"
        static let remakes = "remakes"
        static let remasters = "remasters"
        static let screenshots = "screenshots"
        static let similarGames = "similar_games"
        static let slug = "slug"
        static let standaloneExpansions = "standalone_expansions"
        static let status = "status"
        static let storyline = "storyline"
        static let summary = "summary"
        static let tags = "tags"
        static let themes = "themes"
        static let totalRating = "total_rating"
        static let totalRatingCount = "total_rating_count"
        static let updatedAt = "updated_at"
        static let url = "url"
        static let versionParent = "version_parent"
        static let versionTitle = "version_title"
        static let videos = "videos"
        static let websites = "websites"
    }
    struct GameEngine {
        static let _base = "game_engines"
        static let checksum = "checksum"
        static let companies = "companies"
        static let createdAt = "created_at"
        static let description = "description"
        static let logo = "logo"
        static let name = "name"
        static let platforms = "platforms"
        static let slug = "slug"
        static let updatedAt = "upated_at"
        static let url = "url"
    }
    struct GameEngineLogo {
        static let _base = "game_engine_logos"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let game = "game"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct GameMode {
        static let _base = "game_mode"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct GameVersion {
        static let _base = "game_versions"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let features = "features"
        static let game = "game"
        static let games = "games"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct GameVersionFeature {
        static let _base = "game_version_features"
        static let category = "category"
        static let checksum = "checksum"
        static let description = "description"
        static let position = "position"
        static let title = "titles"
        static let values = "values"
    }
    struct GameVersionFeatureValue {
        static let _base = "game_version_feature_values"
        static let checksum = "checksum"
        static let game = "game"
        static let gameFeature = "game_feature"
        static let includedFeature = "included_feature"
        static let note = "note"
    }
    struct GameVideo {
        static let _base = "game_videos"
        static let checksum = "checksum"
        static let name = "name"
        static let videoId = "video_id"
    }
    struct Genre {
        static let _base = "genres"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct InvolvedCompany {
        static let _base = "involved_companies"
        static let checksum = "checksum"
        static let company = "company"
        static let createdAt = "created_at"
        static let developer = "developer"
        static let game = "game"
        static let porting = "porting"
        static let publisher = "publisher"
        static let supporting = "supporting"
        static let updatedAt = "updated_at"
    }
    struct Keyword {
        static let _base = "keywords"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct MultiplayerMode {
        static let _base = "multiplayer_modes"
        static let campaignCoop = "compaigncoop"
        static let checksum = "checksum"
        static let dropIn = "dropin"
        static let game = "game"
        static let lanCoop = "lancoop"
        static let offlineCoop = "offlinecoop"
        static let offlineCoopMax = "offlinecoopmax"
        static let offlineMax = "offlinemax"
        static let platform = "platform"
        static let splitscreen = "splitscreen"
        static let splitscreenOnline = "splitscreenonline"
    }
    struct Platform {
        static let _base = "platforms"
        static let abbreviation = "abbreviation"
        static let alternativeName = "alternative_name"
        static let category = "category"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let generation = "generation"
        static let name = "name"
        static let platformFamily = "platform_family"
        static let platformLogo = "platform_logo"
        static let slug = "slug"
        static let summary = "summary"
        static let updatedAt = "updated_at"
        static let url = "url"
        static let versions = "versions"
        static let websites = "websites"
    }
    struct PlatformFamily {
        static let _base = "platform_families"
        static let checksum = "checksum"
        static let name = "name"
        static let slug = "slug"
    }
    struct PlatformLogo {
        static let _base = "platform_logos"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let game = "game"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct PlatformVersion {
        static let _base = "platform_versions"
        static let checksum = "checksum"
        static let companies = "companies"
        static let connectivity = "connectivity"
        static let cpu = "cpu"
        static let graphics = "graphics"
        static let mainManufacturer = "main_manufacturer"
        static let media = "media"
        static let memory = "memory"
        static let name = "name"
        static let os = "os"
        static let output = "output"
        static let platformLogo = "platform_logo"
        static let platformVersionReleaseDates = "platform_version_release_dates"
        static let resolutions = "resolutions"
        static let slug = "slug"
        static let sound = "sound"
        static let storage = "storage"
        static let summary = "summary"
        static let url = "url"
    }
    struct PlatformVersionCompany {
        static let _base = "platform_version_companies"
        static let checksum = "checksum"
        static let comment = "comment"
        static let company = "company"
        static let developer = "developer"
        static let manufacturer = "manufacturer"
    }
    struct PlatformVersionReleaseDate {
        static let _base = "platform_version_release_dates"
        static let category = "category"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let date = "date"
        static let human = "human"
        static let month = "m"
        static let platformVersion = "platform_version"
        static let region = "region"
        static let updatedAt = "updated_at"
        static let year = "y"
    }
    struct PlatformWebsite {
        static let _base = "platform_websites"
        static let category = "category"
        static let checksum = "checksum"
        static let trusted = "trusted"
        static let url = "url"
    }
    struct PlayerPerspective {
        static let _base = "player_perspectives"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct ReleaseDate {
        static let _base = "release_dates"
        static let category = "category"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let date = "date"
        static let game = "game"
        static let human = "human"
        static let month = "m"
        static let platform = "platform"
        static let region = "region"
        static let updatedAt = "updated_at"
        static let year = "y"
    }
    struct Screenshot {
        static let _base = "screenshots"
        static let alphaChannel = "alpha_channel"
        static let animated = "animated"
        static let checksum = "checksum"
        static let game = "game"
        static let height = "height"
        static let imageId = "image_id"
        static let url = "url"
        static let width = "width"
    }
    struct Search {
        static let _base = "search"
        static let alternativeName = "alternative_name"
        static let character = "character"
        static let checksum = "checksum"
        static let collection = "collection"
        static let company = "company"
        static let description = "description"
        static let game = "game"
        static let name = "name"
        static let platform = "platform"
        static let publishedAt = "published_at"
        static let testDummy = "test_dummy"
        static let theme = "theme"
    }
    struct Theme {
        static let _base = "themes"
        static let checksum = "checksum"
        static let createdAt = "created_at"
        static let name = "name"
        static let slug = "slug"
        static let updatedAt = "updated_at"
        static let url = "url"
    }
    struct Website {
        static let _base = "websites"
        static let category = "category"
        static let checksum = "checksum"
        static let game = "game"
        static let trusted = "trusted"
        static let url = "url"
    }
}
